{% set name = "mlconjug3" %}
{% set version = "3.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlconjug3-{{ version }}.tar.gz
  sha256: 04a5f604b69a0f3026bc6e0460e85f90f4fcfffb9a00dc3e046898c5bfafd906

build:
  number: 1
  noarch: python
  entry_points:
    - mlconjug3=mlconjug3.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - poetry
  run:
    - click >=8.1.3
    - defusedxml
    - joblib
    - numpy
    - python >={{ python_min }}
    - scikit-learn ==1.3.0
    - rich <13.3
    - pyyaml
    - tomlkit

test:
  imports:
    - mlconjug3
  commands:
    - pip check
    - mlconjug3 --help
  requires:
    - pip
    - poetry
    - python {{ python_min }}

about:
  home: https://github.com/SekouDiaoNlp/mlconjug3
  summary: A Python library to conjugate French, English, Spanish, Italian, Portuguese and Romanian verbs using Machine Learning techniques.
  license: MIT
  license_file: LICENSE
  description: |
    A Command Line application and Python library to conjugate verbs in French, English, Spanish, Italian, Portuguese and Romanian (more soon) using Machine Learning techniques.

    Conjugate any verb in one of the supported languages, even completely new or made-up verbs, with the help of a pre-trained Machine Learning model.
    The pre-trained models are composed of a binary feature extractor, a feature selector using Linear Support Vector Classification, and a classifier using Stochastic Gradient Descent.
    Easily modify and retrain the models using any compatible classifiers from scikit-learn.
    Uses Verbiste as the training data for the French model, and unsupervised learning techniques to generate the data for the English, Spanish, Italian, Portuguese and Romanian models.


    Free software: MIT license

    Documentation: https://mlconjug3.readthedocs.io.

    SUPPORTED LANGUAGES:

    -   French
    -   English
    -   Spanish
    -   Italian
    -   Portuguese
    -   Romanian

    FEATURES:

    -   Command Line Interface tool.
    -   Easy to use and intuitive API.
    -   Includes pre-trained models with 99% + accuracy in predicting conjugation class of unknown verbs.
    -   Easily train new models or add new languages.
    -   Uses caching and multiprocessing for maximum performance.
    -   Easily integrate mlconjug3 in your own projects.
    -   Extensive documentation.
    -   Powerful machine learning algorithms for accurate verb conjugation predictions.
    -   Support for multiple languages including English, Spanish, French, and German.
    -   Customizable settings to fine-tune performance and adapt to different use cases.
    -   Robust error handling and troubleshooting capabilities.
    -   Regular updates and improvements to ensure optimal performance.
    -   Community support and contributions to continuously expand the library’s capabilities.
    -   Integration with popular libraries such as scikit-learn and numpy for machine learning tasks.


    Usage
    =====

    > **note**
    >
    > The default language is French.
    > :   When called without specifying a language, the library will try to
    >     conjugate the verb in French.
    >
    To use MLConjug3 from the command line:

        $ mlconjug3 manger

        $ mlconjug3 bring -l en

        $ mlconjug3 gallofar --language es

        $ mlconjug3 -o, --output (Path of the filename for storing the conjugation tables.)

        $ mlconjug3 -s, --subject (The subject format type for the conjugated forms). The
                           values can be 'abbrev' or 'pronoun'. The default value
                           is 'abbrev'.

        $ mlconjug3 -h Show the help menu
  doc_url: https://mlconjug3.readthedocs.io/en/latest/
  dev_url: https://github.com/SekouDiaoNlp/mlconjug3

extra:
  recipe-maintainers:
    - SekouDiaoNlp
